"""General decoded-script analysis surfaces for Code RED WSC tools."""
from .core import (
    InstructionRow,
    actor_kind,
    branch_rows,
    constant_rows,
    disasm_artifacts,
    disassemble,
    ensure_dir,
    enum_candidates,
    extract_strings,
    find_functions,
    native_rows,
    normalize_terms,
    operand_size,
    patch_candidates,
    write_candidates_report,
    write_csv,
    write_disasm_report,
    write_inspect_report,
    write_json,
    write_map_report,
    write_scan_report,
)
from .control_flow import write_control_flow_report

__all__ = [
    "InstructionRow",
    "actor_kind",
    "branch_rows",
    "constant_rows",
    "disasm_artifacts",
    "disassemble",
    "ensure_dir",
    "enum_candidates",
    "extract_strings",
    "find_functions",
    "native_rows",
    "normalize_terms",
    "operand_size",
    "patch_candidates",
    "write_candidates_report",
    "write_csv",
    "write_disasm_report",
    "write_inspect_report",
    "write_json",
    "write_map_report",
    "write_scan_report",
    "write_control_flow_report",
]
