[General]
; Enabled by default, but in case you still want the intro logos set this to false.
SkipIntroLogos=true

[Scripts]
; Set this to false if you want to disable plugins load on startup.
LoadPluginsOnStartup=true

; Set this to false if you don't want to load .red plugins.
AllowREDPluginsLoading=true

; Set this to true if you want to load .asi plugins. (This is not recommended by default, as it can load potential incompatible plugins)
AllowASIPluginsLoading=false

[DirectXHook]
; Set this to true if you are experiencing crashes or other issues (WARNING: This will completely disable ingame console UI and some other rendering features)
Disabled=false

; Set this to true if you are experiencing no rendering at all (WARNING: This can make the game unstable or fail to launch properly, don't use this if everything is working fine for you)
UseVMT=false

[Misc]
; Set this to false if you want to disable the internal debugging console.
InternalConsole=true

; Set this to true if you want an external debugging console.
ExternalConsole=false