#!/usr/bin/env python3
"""
Code RED Faction War WorldResourceBridge builder.

This is intentionally a no-EXE/no-SC-CL helper. It rebuilds the loose
resource-side bridge files from factionwar_nodes.json and factionwar_factions.json,
and can safely patch an exported game_main.tr text file by adding the Code RED AI
include and world program call.

Usage:
  python WorldResourceBridge/tools/codered_bridge_build.py --root . --build
  python WorldResourceBridge/tools/codered_bridge_build.py --patch-game-main INPUT.tr OUTPUT.tr
"""
from __future__ import annotations

import argparse
import difflib
import json
import re
from collections import defaultdict
from pathlib import Path
from typing import Any, Iterable

ROOT_MARKER = "WorldResourceBridge"
INCLUDE_LINE = '#include "code_red_factionwar_world.tr"'
WORLD_CALL = "CodeRedFactionWarWorld WITH 1.0"

SAFE_TR_TOKENS = {
    "TRUE", "NIL", "Player", "WantToHurt", "Ally", "Hostile", "PossibleEnemy",
    "UnknownWeaponFired", "HiddenEnemyWeaponFired", "RecentExplosion", "ScreamedRecently",
    "ScreamedSomewhatRecently", "ScreamedSinceLastClearlyVisible", "SpatialDistanceClose",
    "SpatialDistanceVeryClose", "CanLookAt", "LookAt", "LookAtIfPossible", "Stay",
    "CanFindAndMoveTo", "FindAndMoveTo", "MoveCloserToWithoutSearch", "CanMoveRetreatFrom",
    "MoveRetreatFrom", "SpeedWalk", "SpeedJog", "SpeedSprint", "CanCombatReadyRangeWeapon",
    "CombatReadyRangeWeapon", "CombatRangeWeaponReadied", "CanCombatShootNoCover",
    "CombatShootNoCover", "CanCombatFightOrTakeDown", "CombatFightOrTakeDown",
    "CanHelp", "Help", "CanObserveLastKnownPosition", "ObserveLastKnownPosition",
    "Search", "AlertedSearch", "UnalertedSearch", "PerformExternalGoals", "UpdateHostility",
    "SpeechEvent", "Mood", "ReportState", "CancelPlannedActivity", "PlanActivity",
    "ActivityReadyToPerform", "EventActive", "Alive", "Riding", "RidingVehicle", "ObjectClassCreatureRaceHuman",
}


def load_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def q(s: str) -> str:
    return str(s).replace('"', "'")


def token_list(value: Any) -> list[str]:
    if isinstance(value, str):
        return [part.strip() for part in value.split(',') if part.strip()]
    if isinstance(value, list):
        return [str(part).strip() for part in value if str(part).strip()]
    return []


def state_for_node(node: dict[str, Any]) -> str:
    tags = set(token_list(node.get("strategic_tags")))
    context = node.get("context_tag", "")
    controller = node.get("default_controller", "")
    if "law_hub" in tags or context in {"law_town", "rail_checkpoint"}:
        return "marshal_roadblock"
    if "transport_post" in tags or "escort" in context or "border" in context:
        return "wagon_route"
    if "outlaw_hideout" in tags or "raid_origin" in tags or context in {"camp_hideout", "rustler_hideout", "roadside_robbery"}:
        return "outlaw_watchtrail"
    if "war_anchor" in tags or "fortified_outpost" in tags or controller in {"MexicanBandito", "IndianRaider"}:
        return "raider_corridor"
    if "black_market" in tags or context == "black_market":
        return "smuggler_lane"
    if "resource_node" in tags or "mine" in context or "loot_zone" in tags:
        return "salvage_track"
    return "frontier_open"


def population_profile_for_node(node: dict[str, Any]) -> str:
    tags = set(token_list(node.get("strategic_tags")))
    context = node.get("context_tag", "")
    controller = node.get("default_controller", "")
    if controller == "USLawEnforcement" or "law_hub" in tags:
        return "marshal_heavy" if node.get("base_pressure", 0) >= 55 else "deputy_watch"
    if controller in {"CattleRustler", "MexicanBandito", "IndianRaider", "TreasureHunter", "GenericCriminal"}:
        if "transport_post" in tags or context == "black_market":
            return "smuggler_wagons"
        return "gang_muster"
    if "supply_node" in tags or "civilian_defense" in tags:
        return "settlers_and_traders"
    if "ghost_town" in tags or "resource_node" in tags:
        return "scavengers_and_miners"
    return "mixed_frontier"


def write_if_changed(path: Path, text: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    old = path.read_text(encoding="utf-8") if path.exists() else None
    if old == text:
        return False
    path.write_text(text, encoding="utf-8", newline="\n")
    return True


def build_tr(nodes: list[dict[str, Any]], factions: list[dict[str, Any]]) -> str:
    regions: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for node in nodes:
        regions[node["region_name"]].append(node)

    lines: list[str] = []
    lines += [
        "// Code RED Faction War no-SC AI bridge",
        "// Generated by WorldResourceBridge/tools/codered_bridge_build.py.",
        "// Uses condition/action names observed in recovered game_main/human TR files.",
        "// Intended injection point: root/content/ai/game_main.tr or root/tune/ai/game_main.tr.",
        "// Do not blind-inject until Code RED validates the target archive rebuild.",
        "",
        "rules Rules_CodeRedFactionWarSignals",
        "{",
        "\t// Reuse native TR perception/combat conditions to emit Code RED tags.",
        "\tPlayer(x) && WantToHurt(x) && Alive(x)\t\t\t\t\t->\tCodeRedFactionWarEnemy(x);",
        "\tHostile(x) && SpatialDistanceClose(x) && Alive(x)\t\t\t->\tCodeRedFactionWarCloseHostile(x);",
        "\tPossibleEnemy(x) && SpatialDistanceClose(x) && CanLookAt(x)\t->\tCodeRedFactionWarSuspicious(x);",
        "\tAlly(x) && ScreamedRecently(x) && SpatialDistanceClose(x)\t\t->\tCodeRedFactionWarAllyNeedsHelp(x);",
        "\tUnknownWeaponFired(x) && CanObserveLastKnownPosition(x)\t\t->\tCodeRedFactionWarGunfire(x);",
        "\tHiddenEnemyWeaponFired(x) && CanObserveLastKnownPosition(x)\t\t->\tCodeRedFactionWarGunfire(x);",
        "\tRecentExplosion(x) && CanObserveLastKnownPosition(x)\t\t\t->\tCodeRedFactionWarExplosion(x);",
        "}",
        "",
        "program CodeRedFactionWarWorld",
        "{",
        "\t// Run light-touch frontier behavior before falling back to stock external goals.",
        "\tTRUE\t->\tCodeRedFactionWarCombatPulse, CodeRedFactionWarRoadPulse, CodeRedFactionWarCivilianPulse, PerformExternalGoals;",
        "}",
        "",
        "program CodeRedFactionWarCombatPulse",
        "{",
        "\tCodeRedFactionWarCloseHostile(x) && CanCombatFightOrTakeDown(x)\t->\tCombatFightOrTakeDown(x), SpeechEvent(\"HostileFight\"), Mood(\"HOSTILE\");",
        "\tCodeRedFactionWarEnemy(x) && !CombatRangeWeaponReadied && CanCombatReadyRangeWeapon\t->\tCombatReadyRangeWeapon, LookAtIfPossible(x);",
        "\tCodeRedFactionWarEnemy(x) && CanCombatShootNoCover(x)\t\t\t->\tCombatShootNoCover(x), SpeechEvent(\"HostileFight\");",
        "\tCodeRedFactionWarSuspicious(x) && CanLookAt(x)\t\t\t\t->\tLookAt(x), Mood(\"HOSTILE\");",
        "\tTRUE\t->\tNIL;",
        "}",
        "",
        "program CodeRedFactionWarRoadPulse",
        "{",
        "\tCodeRedFactionWarGunfire(x)\t\t->\tObserveLastKnownPosition(x), SpeedJog;",
        "\tCodeRedFactionWarExplosion(x)\t\t->\tObserveLastKnownPosition(x), SpeedSprint;",
        "\tTRUE\t->\tNIL;",
        "}",
        "",
        "program CodeRedFactionWarCivilianPulse",
        "{",
        "\tCodeRedFactionWarAllyNeedsHelp(x) && CanHelp(x)\t->\tHelp(x), SpeedSprint;",
        "\tTRUE\t->\tNIL;",
        "}",
        "",
        "// Region/node metadata below is for Code RED merge tools and future targeted predicates.",
        "// It is deliberately stored as comments so unsupported tokens cannot crash TR parsing.",
    ]
    for region, region_nodes in sorted(regions.items()):
        lines.append(f"// region {q(region)}")
        for n in region_nodes:
            tags = ','.join(token_list(n.get('strategic_tags')))
            lines.append(
                f"// node {q(n['node_id'])}: display=\"{q(n['display_name'])}\" controller={q(n['default_controller'])} "
                f"road={state_for_node(n)} population={population_profile_for_node(n)} tags={q(tags)}"
            )
    lines.append("")
    return "\n".join(lines)


def build_pop(nodes: list[dict[str, Any]], factions: list[dict[str, Any]]) -> str:
    regions = sorted({n["region_name"] for n in nodes})
    lines: list[str] = [
        "version 2",
        "{",
        "\t// Code RED Faction War population bridge generated from v26 seed data.",
        "\t// Matches the level.pop condition/profile style found in tune_d11generic.rpf.",
        "\tConditions",
        "\t{",
        "\t\tCondition \"cond_codered_night\"",
        "\t\t{",
        "\t\t\tExpression \"TimeOfDay(night)\"",
        "\t\t}",
    ]
    for region in regions:
        lines += [
            f"\t\tCondition \"cond_codered_{region}\"",
            "\t\t{",
            f"\t\t\tExpression \"Neighborhood({region})\"",
            "\t\t}",
        ]
    for faction in factions:
        faction_name = faction.get("engine_faction") or faction.get("engineFaction") or faction.get("engineFactionName") or faction.get("engineFaction", "")
        if faction_name:
            lines += [
                f"\t\tCondition \"cond_codered_{faction_name}\"",
                "\t\t{",
                f"\t\t\tExpression \"Faction({faction_name})\"",
                "\t\t}",
            ]
    lines += ["\t}", "\tProfiles", "\t{"]
    profile_names = sorted({population_profile_for_node(n) for n in nodes})
    for profile in profile_names:
        lines += [
            f"\t\tProfile \"codered_{profile}\"",
            "\t\t{",
            f"\t\t\tLabel \"{profile}\"",
            "\t\t\tSpawnBias 1.000000",
            "\t\t}",
        ]
    lines += ["\t}", "\tNodes", "\t{"]
    for n in nodes:
        tags = ','.join(token_list(n.get('strategic_tags')))
        lines += [
            f"\t\tNode \"{q(n['node_id'])}\"",
            "\t\t{",
            f"\t\t\tDisplayName \"{q(n['display_name'])}\"",
            f"\t\t\tRegion \"{q(n['region_name'])}\"",
            f"\t\t\tController \"{q(n['default_controller'])}\"",
            f"\t\t\tContext \"{q(n.get('context_tag',''))}\"",
            f"\t\t\tPopulationProfile \"codered_{population_profile_for_node(n)}\"",
            f"\t\t\tCivilianArchetype \"{q(n.get('civilian_archetype',''))}\"",
            f"\t\t\tOutlawArchetype \"{q(n.get('outlaw_archetype',''))}\"",
            f"\t\t\tLawArchetype \"{q(n.get('law_archetype',''))}\"",
            f"\t\t\tBasePressure {int(n.get('base_pressure',0))}",
            f"\t\t\tBaseHeat {int(n.get('base_heat',0))}",
            f"\t\t\tStrategicTags \"{q(tags)}\"",
            "\t\t}",
        ]
    lines += ["\t}", "}", ""]
    return "\n".join(lines)


def build_traffic(nodes: list[dict[str, Any]]) -> str:
    lines: list[str] = [
        "version 1",
        "{",
        "\t// Code RED Faction War traffic/road-control bridge.",
        "\t// default.traffic in the scanned tune archive is small, so this is generated as a merge block.",
        f"\tProfileCount {len(nodes)}",
        "\t{",
        "\t\tProfileRecords 0",
        "\t\t{",
    ]
    for n in nodes:
        neighbors = ','.join(token_list(n.get('neighbors')))
        lines += [
            f"\t\t\tRouteProfile \"codered_{q(n['node_id'])}\"",
            "\t\t\t{",
            f"\t\t\t\tRegion \"{q(n['region_name'])}\"",
            f"\t\t\t\tState \"{state_for_node(n)}\"",
            f"\t\t\t\tNeighbors \"{q(neighbors)}\"",
            f"\t\t\t\tHeat {int(n.get('base_heat',0))}",
            f"\t\t\t\tPressure {int(n.get('base_pressure',0))}",
            "\t\t\t}",
        ]
    lines += ["\t\t}", "\t}", "}", ""]
    return "\n".join(lines)


def build_world_ini(nodes: list[dict[str, Any]], factions: list[dict[str, Any]]) -> str:
    lines = [
        "; Code RED Faction War world state bridge",
        "; Generated no-SC/no-menu editable data. The RedHook branch can read this later, and Code RED can use it as a patch manifest.",
        "[bridge]",
        "version=pass02",
        "resource_lane=ai_tr_pop_traffic",
        "",
        "[factions]",
    ]
    for f in factions:
        name = f.get("engine_faction") or f.get("engineFaction") or f.get("engineFactionName") or f.get("engineFaction", "")
        brand = f.get("brand_name") or f.get("brandName") or name
        if name:
            lines.append(f"{name}={brand}")
    lines += ["", "[nodes]"]
    for n in nodes:
        anchor = n.get("anchor", {})
        tags = ','.join(token_list(n.get('strategic_tags')))
        neighbors = ','.join(token_list(n.get('neighbors')))
        lines.append(
            f"{n['node_id']}={n['display_name']}|{n['region_name']}|{n['default_controller']}|"
            f"{neighbors}|{tags}|{n.get('base_pressure',0)}|{n.get('base_heat',0)}|"
            f"{anchor.get('x',0)}|{anchor.get('y',0)}|{anchor.get('z',0)}|{anchor.get('heading',0)}|"
            f"{n.get('context_tag','')}|{state_for_node(n)}|{population_profile_for_node(n)}"
        )
    lines.append("")
    return "\n".join(lines)


def patch_game_main_text(text: str) -> str:
    if INCLUDE_LINE not in text:
        include_matches = list(re.finditer(r'^#include\s+"[^"]+"\s*$', text, flags=re.MULTILINE))
        if include_matches:
            insert_at = include_matches[-1].end()
            text = text[:insert_at] + "\n" + INCLUDE_LINE + text[insert_at:]
        else:
            text = INCLUDE_LINE + "\n" + text

    # Patch the first TRUE route inside program Main only.
    main_match = re.search(r'(program\s+Main\s*\{)(.*?)(\n\})', text, flags=re.DOTALL)
    if not main_match:
        raise ValueError("Could not find 'program Main { ... }' block")
    main_body = main_match.group(2)
    if WORLD_CALL not in main_body:
        route_re = re.compile(r'(^\s*TRUE\s*->\s*[^;]+)(;)', flags=re.MULTILINE)
        m = route_re.search(main_body)
        if not m:
            raise ValueError("Could not find TRUE -> route inside program Main")
        replacement = m.group(1).rstrip() + ", " + WORLD_CALL + m.group(2)
        main_body = main_body[:m.start()] + replacement + main_body[m.end():]
        text = text[:main_match.start(2)] + main_body + text[main_match.end(2):]
    return text


def brace_balance(text: str) -> int:
    stripped = re.sub(r'//.*', '', text)
    return stripped.count('{') - stripped.count('}')


def validate_outputs(root: Path) -> list[str]:
    notes: list[str] = []
    bridge = root / ROOT_MARKER
    for rel in [
        "tune_ai/code_red_factionwar_world.tr",
        "tune_level/code_red_factionwar_level.pop",
        "tune_settings/code_red_factionwar.traffic",
        "world_state_bridge.ini",
    ]:
        p = bridge / rel
        text = p.read_text(encoding="utf-8")
        bal = brace_balance(text)
        notes.append(f"{rel}: bytes={p.stat().st_size} brace_balance={bal}")
        if bal != 0:
            raise ValueError(f"Brace mismatch in {rel}: {bal}")
    tr_text = (bridge / "tune_ai/code_red_factionwar_world.tr").read_text(encoding="utf-8")
    forbidden = ["FactionPressure(", "Neighborhood(t_", "Magic", "SC-CL"]
    for token in forbidden:
        if token in tr_text:
            raise ValueError(f"Forbidden/unsupported TR token present: {token}")
    notes.append("TR unsupported-token check: passed")
    return notes


def build(root: Path) -> list[str]:
    bridge = root / ROOT_MARKER
    nodes = load_json(bridge / "factionwar_nodes.json")
    factions = load_json(bridge / "factionwar_factions.json")
    changed: list[str] = []
    outputs = {
        bridge / "tune_ai/code_red_factionwar_world.tr": build_tr(nodes, factions),
        bridge / "merge_packs/content_ai/root_content_ai_code_red_factionwar_world.tr": build_tr(nodes, factions),
        bridge / "merge_packs/tune_ai/root_tune_ai_code_red_factionwar_world.tr": build_tr(nodes, factions),
        bridge / "tune_level/code_red_factionwar_level.pop": build_pop(nodes, factions),
        bridge / "merge_packs/tune_level/root_tune_level_territory_code_red_factionwar_level.pop": build_pop(nodes, factions),
        bridge / "tune_settings/code_red_factionwar.traffic": build_traffic(nodes),
        bridge / "merge_packs/tune_settings/root_tune_settings_code_red_factionwar.traffic": build_traffic(nodes),
        bridge / "world_state_bridge.ini": build_world_ini(nodes, factions),
    }
    for path, text in outputs.items():
        if write_if_changed(path, text):
            changed.append(str(path.relative_to(root)))

    recipe = {
        "name": "Code RED Faction War No-SC Menu-Free World Bridge",
        "version": "pass02",
        "mode": "no_exe_no_sccl_resource_merge",
        "safe_order": [
            "1_extract_target_tr_text",
            "2_patch_game_main_include_and_true_route",
            "3_add_code_red_factionwar_world_tr_as_loose_resource_or_archive_entry",
            "4_merge_population_and_traffic_only_after parser validation",
            "5_recompress_zstandard_when original entry uses zstd",
            "6_reopen_archive_and verify bytes/text"
        ],
        "targets": [
            {
                "archive": "content.rpf",
                "candidate": "root/content/ai/game_main.tr",
                "operation": "insert_include_and_add_world_program_to_Main_TRUE_route",
                "include": INCLUDE_LINE,
                "call": WORLD_CALL,
                "source": "WorldResourceBridge/merge_packs/content_ai/root_content_ai_code_red_factionwar_world.tr"
            },
            {
                "archive": "tune_d11generic.rpf",
                "candidate": "root/tune/ai/game_main.tr",
                "operation": "insert_include_and_add_world_program_to_Main_TRUE_route",
                "include": INCLUDE_LINE,
                "call": WORLD_CALL,
                "source": "WorldResourceBridge/merge_packs/tune_ai/root_tune_ai_code_red_factionwar_world.tr"
            },
            {
                "archive": "tune_d11generic.rpf",
                "candidate": "root/tune/level/territory/level.pop",
                "operation": "merge_generated_population_profiles_after_parser_support",
                "source": "WorldResourceBridge/tune_level/code_red_factionwar_level.pop"
            },
            {
                "archive": "tune_d11generic.rpf",
                "candidate": "root/tune/settings/default.traffic",
                "operation": "merge_generated_route_profiles_after_parser_support",
                "source": "WorldResourceBridge/tune_settings/code_red_factionwar.traffic"
            }
        ],
        "notes": [
            "Pass02 stops using fake TR functions. The TR bridge uses condition/action names observed in recovered human AI files.",
            "The .pop and .traffic files are merge blocks, not blind replacements.",
            "Use Code RED's Zstandard resource path for entries beginning with 28 B5 2F FD."
        ]
    }
    recipe_text = json.dumps(recipe, indent=2)
    if write_if_changed(bridge / "patch_recipes/code_red_factionwar_world_bridge_recipe.json", recipe_text + "\n"):
        changed.append("WorldResourceBridge/patch_recipes/code_red_factionwar_world_bridge_recipe.json")

    notes = validate_outputs(root)
    report = ["Code RED Faction War WorldResourceBridge Pass02 validation", "", *notes, "", "Changed files:", *(changed or ["none"]), ""]
    write_if_changed(bridge / "VALIDATION_BRIDGE_PASS02.txt", "\n".join(report))
    return report


def make_patch_preview(input_path: Path, output_path: Path) -> str:
    source = input_path.read_text(encoding="utf-8", errors="replace")
    patched = patch_game_main_text(source)
    write_if_changed(output_path, patched)
    diff = "\n".join(difflib.unified_diff(
        source.splitlines(), patched.splitlines(),
        fromfile=str(input_path), tofile=str(output_path), lineterm=""
    ))
    diff_path = output_path.with_suffix(output_path.suffix + ".diff")
    write_if_changed(diff_path, diff + "\n")
    return diff


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".", help="Project root containing WorldResourceBridge")
    parser.add_argument("--build", action="store_true", help="Regenerate bridge files")
    parser.add_argument("--patch-game-main", nargs=2, metavar=("INPUT_TR", "OUTPUT_TR"), help="Patch exported game_main.tr text")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    if args.build:
        report = build(root)
        print("\n".join(report))
    if args.patch_game_main:
        diff = make_patch_preview(Path(args.patch_game_main[0]), Path(args.patch_game_main[1]))
        print(diff or "No diff; target already patched.")
    if not args.build and not args.patch_game_main:
        parser.print_help()
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
