#!/usr/bin/env python3
"""Prepare a safe CodeRED AI Menu native bridge integration candidate.

This tool does not overwrite or install CodeRED_AI_Menu.cpp. It creates a
candidate source file that includes the selected native wrappers generated by
`tools/codered_native_bridge_generation.py`, writes a Windows build helper for
that candidate, and emits proof reports.
"""
from __future__ import annotations

import argparse
import difflib
import json
import re
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Sequence

VERSION = "1.0.0-ai-menu-bridge-integration-prep"
SOURCE_REL = Path("related_apps/Code_RED_ScriptHookRDR_AI_Menu/CodeRED_AI_Menu.cpp")
CANDIDATE_REL = Path("related_apps/Code_RED_ScriptHookRDR_AI_Menu/CodeRED_AI_Menu.bridge_candidate.cpp")
BUILD_REL = Path("related_apps/Code_RED_ScriptHookRDR_AI_Menu/build_bridge_candidate.bat")
WRAPPERS_REL = Path("data/codered/native_bridge_selected_wrappers.cpp")
MANIFEST_REL = Path("data/codered/native_bridge_manifest.json")
OUT_MANIFEST_REL = Path("data/codered/ai_menu_bridge_integration_manifest.json")
REPORT_JSON_REL = Path("logs/CodeRED_AI_Menu_Bridge_Integration_Report.json")
REPORT_MD_REL = Path("logs/CodeRED_AI_Menu_Bridge_Integration_Report.md")
DIFF_REL = Path("logs/CodeRED_AI_Menu_Bridge_Integration_Candidate.diff")
PASS_LOG_REL = Path("logs/CodeRED_AI_Menu_Bridge_Integration_Lane_Pass_2026-05-03.md")
BEGIN_MARKER = "// BEGIN CODERED_NATIVE_BRIDGE_SELECTED_WRAPPERS"
END_MARKER = "// END CODERED_NATIVE_BRIDGE_SELECTED_WRAPPERS"
INSERT_BEFORE = "\nstatic bool nativeReady()"

REQUIRED_EXISTING_NATIVE_LABELS = (
    "CREATE_ACTOR_IN_LAYOUT",
    "TASK_FOLLOW_ACTOR",
    "TASK_KILL_CHAR",
    "SET_ACTOR_FACTION",
    "GET_ACTOR_FACTION",
    "AI_IS_HOSTILE_OR_ENEMY",
)

HASH_TO_LABEL = {
    "0x8D67F397": "CREATE_ACTOR_IN_LAYOUT",
    "0x12F0911A": "TASK_FOLLOW_ACTOR",
    "0x1AE4B75B": "TASK_KILL_CHAR",
    "0xCC63951A": "SET_ACTOR_FACTION",
    "0x52E2A611": "GET_ACTOR_FACTION",
    "0x9AB964F4": "AI_IS_HOSTILE_OR_ENEMY",
}

@dataclass
class IntegrationReport:
    version: str
    generated_utc: str
    ok: bool
    source: str
    candidate: str
    wrappers: str
    selected_natives: int
    ready_wrappers: int
    inserted: bool
    build_helper: str
    diff: str
    manifest: str
    report_markdown: str
    report_json: str
    existing_native_usage: dict[str, int]
    warnings: list[str]
    errors: list[str]


def utc_now() -> str:
    return datetime.now(UTC).isoformat(timespec="seconds").replace("+00:00", "Z")


def read_json(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


def count_ready_wrappers(wrapper_text: str) -> int:
    return len(re.findall(r"\bstatic\s+[^;{]+\s+CR_NATIVE_[A-Z0-9_]+\s*\(", wrapper_text))


def selected_count(manifest: dict, wrapper_text: str) -> int:
    values = manifest.get("selected") or manifest.get("natives") or manifest.get("records")
    if isinstance(values, list):
        return len(values)
    specs = re.findall(r"\{\s*\"[A-Z0-9_]+\"\s*,\s*0x[0-9A-Fa-f]+ULL", wrapper_text)
    return len(specs)


def strip_existing_bridge_block(source: str) -> str:
    if BEGIN_MARKER not in source:
        return source
    pattern = re.compile(re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER) + r"\n?", re.DOTALL)
    return pattern.sub("", source)


def build_candidate(source_text: str, wrapper_text: str) -> tuple[str, list[str], list[str]]:
    warnings: list[str] = []
    errors: list[str] = []
    clean_source = strip_existing_bridge_block(source_text)
    if "template <typename R" not in clean_source or "nativeInvoke" not in clean_source:
        errors.append("Could not verify existing nativeInvoke template helper in AI Menu source.")
    if "namespace codered" not in clean_source:
        errors.append("Could not verify outer namespace codered in AI Menu source.")
    if INSERT_BEFORE not in clean_source:
        errors.append("Could not find stable insertion marker before nativeReady().")
        return source_text, warnings, errors
    if "namespace codered_native_bridge" not in wrapper_text:
        errors.append("Selected native wrapper file does not contain codered_native_bridge namespace.")
    block = "\n".join([
        BEGIN_MARKER,
        "// Generated candidate block. Do not hand-edit this section in-place.",
        "// Re-run tools/codered_ai_menu_bridge_integration.py after regenerating native wrappers.",
        wrapper_text.strip(),
        END_MARKER,
        "",
    ])
    candidate = clean_source.replace(INSERT_BEFORE, "\n" + block + INSERT_BEFORE, 1)
    return candidate, warnings, errors


def native_usage_counts(source_text: str) -> dict[str, int]:
    counts: dict[str, int] = {}
    for hash_text, label in HASH_TO_LABEL.items():
        counts[label] = source_text.upper().count(hash_text.upper())
    return counts


def write_candidate_build_helper(root: Path, candidate: Path) -> Path:
    build = root / BUILD_REL
    build.parent.mkdir(parents=True, exist_ok=True)
    rel_candidate = str(candidate.relative_to(root)).replace("/", "\\")
    content = f"""@echo off
setlocal

rem CodeRED AI Menu candidate bridge build helper.
rem Run from the repository root in a Visual Studio x64 Native Tools Command Prompt.
rem This builds the generated bridge-candidate source and does not overwrite the normal ASI.

set OUTDIR=related_apps\\Code_RED_ScriptHookRDR_AI_Menu\\build_bridge_candidate
set SRC={rel_candidate}
set OUT=%OUTDIR%\\CodeRED_AI_Menu_bridge_candidate.asi
set OBJ=%OUTDIR%\\CodeRED_AI_Menu_bridge_candidate.obj
set PDB=%OUTDIR%\\CodeRED_AI_Menu_bridge_candidate.pdb
set IMPLIB=%OUTDIR%\\CodeRED_AI_Menu_bridge_candidate.lib

if not exist "%OUTDIR%" mkdir "%OUTDIR%"

where cl >nul 2>nul
if errorlevel 1 (
  echo [ERROR] cl.exe was not found.
  echo Open "x64 Native Tools Command Prompt for VS" or install Visual Studio Build Tools.
  exit /b 1
)

cl /std:c++17 /EHsc /LD /nologo "%SRC%" /Fo"%OBJ%" /Fd"%PDB%" /Fe"%OUT%" /link /OUT:"%OUT%" /IMPLIB:"%IMPLIB%" user32.lib
if errorlevel 1 (
  echo [ERROR] Candidate bridge build failed.
  exit /b 1
)

echo.
echo Built candidate: %OUT%
echo This is a proof artifact. Do not install until runtime testing is planned.
endlocal
"""
    build.write_text(content, encoding="utf-8", newline="")
    return build


def write_diff(path: Path, source_text: str, candidate_text: str, source_name: str, candidate_name: str) -> None:
    lines = difflib.unified_diff(
        source_text.splitlines(),
        candidate_text.splitlines(),
        fromfile=source_name,
        tofile=candidate_name,
        lineterm="",
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_markdown(report: IntegrationReport) -> str:
    lines = [
        "# CodeRED AI Menu Bridge Integration Report",
        "",
        f"Generated: `{report.generated_utc}`",
        f"Result: **{'PASS' if report.ok else 'FAIL'}**",
        "",
        "## Outputs",
        "",
        f"- Source: `{report.source}`",
        f"- Candidate: `{report.candidate}`",
        f"- Build helper: `{report.build_helper}`",
        f"- Diff: `{report.diff}`",
        f"- Manifest: `{report.manifest}`",
        "",
        "## Native bridge wrapper proof",
        "",
        f"- Selected natives: `{report.selected_natives}`",
        f"- Ready wrappers: `{report.ready_wrappers}`",
        f"- Candidate block inserted: `{report.inserted}`",
        "",
        "## Existing AI Menu native usage",
        "",
    ]
    for label, count in sorted(report.existing_native_usage.items()):
        lines.append(f"- `{label}`: `{count}` hash references")
    if report.warnings:
        lines.extend(["", "## Warnings", ""])
        lines.extend(f"- {item}" for item in report.warnings)
    if report.errors:
        lines.extend(["", "## Errors", ""])
        lines.extend(f"- {item}" for item in report.errors)
    lines.extend([
        "",
        "## Safety note",
        "",
        "This pass does not overwrite the active AI Menu source and does not install an ASI.",
        "Use the generated candidate and build helper only after reviewing the diff.",
    ])
    return "\n".join(lines) + "\n"


def run(root: Path) -> IntegrationReport:
    source = root / SOURCE_REL
    wrappers = root / WRAPPERS_REL
    manifest_path = root / MANIFEST_REL
    out_manifest = root / OUT_MANIFEST_REL
    report_json = root / REPORT_JSON_REL
    report_md = root / REPORT_MD_REL
    diff_path = root / DIFF_REL
    pass_log = root / PASS_LOG_REL
    candidate = root / CANDIDATE_REL

    errors: list[str] = []
    warnings: list[str] = []
    if not source.exists():
        errors.append(f"Missing AI Menu source: {source}")
        source_text = ""
    else:
        source_text = source.read_text(encoding="utf-8", errors="ignore")
    if not wrappers.exists():
        errors.append(f"Missing selected wrapper source: {wrappers}")
        wrapper_text = ""
    else:
        wrapper_text = wrappers.read_text(encoding="utf-8", errors="ignore")

    manifest = read_json(manifest_path)
    selected = selected_count(manifest, wrapper_text)
    ready = count_ready_wrappers(wrapper_text)
    existing_usage = native_usage_counts(source_text)
    for label in REQUIRED_EXISTING_NATIVE_LABELS:
        if existing_usage.get(label, 0) <= 0:
            warnings.append(f"Existing AI Menu source did not reference expected native hash for {label}.")

    candidate_text = source_text
    inserted = False
    if source_text and wrapper_text:
        candidate_text, build_warnings, build_errors = build_candidate(source_text, wrapper_text)
        warnings.extend(build_warnings)
        errors.extend(build_errors)
        inserted = BEGIN_MARKER in candidate_text and END_MARKER in candidate_text
        if inserted and not errors:
            candidate.parent.mkdir(parents=True, exist_ok=True)
            candidate.write_text(candidate_text, encoding="utf-8")
            write_diff(diff_path, source_text, candidate_text, str(SOURCE_REL), str(CANDIDATE_REL))
    build_helper = write_candidate_build_helper(root, candidate)

    if selected <= 0:
        errors.append("No selected native bridge records were found.")
    if ready <= 0:
        errors.append("No ready CR_NATIVE_* wrappers were found.")
    if ready and selected and ready < selected:
        warnings.append(f"Ready wrapper count {ready} is below selected native count {selected}.")

    ok = inserted and ready > 0 and selected > 0 and not errors
    report = IntegrationReport(
        version=VERSION,
        generated_utc=utc_now(),
        ok=ok,
        source=str(source),
        candidate=str(candidate),
        wrappers=str(wrappers),
        selected_natives=selected,
        ready_wrappers=ready,
        inserted=inserted,
        build_helper=str(build_helper),
        diff=str(diff_path),
        manifest=str(out_manifest),
        report_markdown=str(report_md),
        report_json=str(report_json),
        existing_native_usage=existing_usage,
        warnings=warnings,
        errors=errors,
    )
    out_manifest.parent.mkdir(parents=True, exist_ok=True)
    report_json.parent.mkdir(parents=True, exist_ok=True)
    payload = asdict(report)
    out_manifest.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    report_json.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    markdown = write_markdown(report)
    report_md.write_text(markdown, encoding="utf-8")
    pass_log.write_text(
        "# CodeRED AI Menu Bridge Integration Lane Pass - 2026-05-03\n\n"
        + markdown
        + "\n## Next step\n\nRun `related_apps\\Code_RED_ScriptHookRDR_AI_Menu\\build_bridge_candidate.bat` from a Visual Studio x64 Native Tools Command Prompt on Windows.\n",
        encoding="utf-8",
    )
    return report


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Prepare a safe AI Menu native bridge integration candidate.")
    p.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    return p


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    report = run(args.root.resolve())
    print(f"AI Menu bridge integration: {'PASS' if report.ok else 'FAIL'}")
    print(f"Selected natives: {report.selected_natives}")
    print(f"Ready wrappers:    {report.ready_wrappers}")
    print(f"Candidate:         {report.candidate}")
    print(f"Build helper:      {report.build_helper}")
    print(f"Report:            {report.report_markdown}")
    if report.errors:
        for item in report.errors:
            print(f"ERROR: {item}")
    if report.warnings:
        for item in report.warnings:
            print(f"WARN: {item}")
    return 0 if report.ok else 2


if __name__ == "__main__":
    raise SystemExit(main())
