#!/usr/bin/env python3
"""Code RED Companion command writer.

Writes safe command lines for the CodeREDCompanion ASI proof lane.
Pass 0.3 only writes commands. The ASI still executes no actor/game actions.
"""

from __future__ import annotations

import argparse
import hashlib
from datetime import datetime
from pathlib import Path
from typing import Iterable

SAFE_COMMANDS = {"PING", "STATUS", "VERSION", "HELP"}
FUTURE_COMMANDS = {
    "SPAWN_ACTOR",
    "FOLLOW",
    "GUARD",
    "ATTACK",
    "DISMISS",
    "MOUNT",
    "WAYPOINT",
    "TELEPORT",
    "SET_FORMATION",
}
ACTOR_WHITELIST = {
    "ACTOR_CAUCASIAN_ARMY_EASY01",
    "AE_CAUCASIAN_ARMY_EASY01",
    "ACTOR_CAUCASIAN_MALE_TOWNFOLK02",
    "ACTOR_RIDEABLE_ANIMAL_HORSE01",
    "ACTOR_RIDEABLE_ANIMAL_MEX_MULE01",
    "ACTOR_VEHICLE_CAR01",
    "ACTOR_VEHICLE_TRUCK01",
    "ACTOR_VEHICLE_STAGECOACH",
    "ACTOR_VEHICLE_WAGON02",
    "ACTOR_VEHICLE_COACH01",
}


def utc_stamp() -> str:
    return datetime.utcnow().strftime("%Y%m%d_%H%M%S_%f")


def stable_id(command_body: str) -> str:
    digest = hashlib.sha1(command_body.encode("utf-8", errors="replace")).hexdigest()[:12]
    return f"cmd_{utc_stamp()}_{digest}"


def normalize_actor(actor: str | None) -> str:
    return (actor or "").strip()


def validate_command(command: str, actor: str | None) -> tuple[str, str]:
    verb = command.strip().upper()
    actor_name = normalize_actor(actor)

    if verb in SAFE_COMMANDS:
        return verb, actor_name

    if verb in FUTURE_COMMANDS:
        if not actor_name and verb in {"SPAWN_ACTOR", "FOLLOW", "GUARD", "ATTACK", "DISMISS", "MOUNT"}:
            raise ValueError(f"{verb} needs --actor for the proof command file")
        if actor_name and actor_name.upper() not in ACTOR_WHITELIST:
            raise ValueError(
                f"Actor is not in the Pass 0.3 whitelist: {actor_name}\n"
                f"Allowed: {', '.join(sorted(ACTOR_WHITELIST))}"
            )
        return verb, actor_name

    raise ValueError(
        f"Unsupported command: {command}\n"
        f"Safe: {', '.join(sorted(SAFE_COMMANDS))}\n"
        f"Future/blocked: {', '.join(sorted(FUTURE_COMMANDS))}"
    )


def command_body(verb: str, actor: str, extra_args: Iterable[str]) -> str:
    parts = [verb]
    if actor:
        parts.append(actor)
    parts.extend(arg.strip() for arg in extra_args if arg.strip())
    return " ".join(parts)


def default_command_path(game_root: Path) -> Path:
    return game_root / "data" / "codered" / "companion_commands.txt"


def write_command(path: Path, line: str, append: bool) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    mode = "a" if append and path.exists() else "w"
    with path.open(mode, encoding="utf-8", newline="\n") as handle:
        if mode == "w":
            handle.write("# CodeREDCompanion command file. Generated by tools/codered_companion_command_writer.py\n")
            handle.write("# Pass 0.3 validates commands but executes no actor/game actions.\n")
        handle.write(line.rstrip() + "\n")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Write CodeREDCompanion ASI proof commands.")
    parser.add_argument("command", help="PING, STATUS, VERSION, HELP, or a future blocked command like SPAWN_ACTOR")
    parser.add_argument("extra", nargs="*", help="Extra command arguments after the actor")
    parser.add_argument("--actor", help="Actor name for future actor commands")
    parser.add_argument("--id", dest="command_id", help="Explicit command id. Defaults to a timestamp/hash id")
    parser.add_argument("--game-root", type=Path, default=Path.cwd(), help="Folder containing the game executable")
    parser.add_argument("--command-file", type=Path, help="Override companion_commands.txt path")
    parser.add_argument("--replace", action="store_true", help="Replace the command file instead of appending")
    parser.add_argument("--dry-run", action="store_true", help="Print the command line without writing")
    return parser


def main() -> int:
    args = build_parser().parse_args()
    verb, actor = validate_command(args.command, args.actor)
    body = command_body(verb, actor, args.extra)
    command_id = args.command_id or stable_id(body)
    line = f"ID={command_id} {body}"
    path = args.command_file or default_command_path(args.game_root)

    if args.dry_run:
        print(line)
        print(f"target={path}")
        return 0

    write_command(path, line, append=not args.replace)
    print(f"Wrote: {line}")
    print(f"Path:  {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
