#include "SectorPatchQueue.h"
#include <sstream>

namespace codered {

std::string toString(SectorPatchAction action) {
    switch (action) {
    case SectorPatchAction::Enable: return "enable";
    case SectorPatchAction::Disable: return "disable";
    case SectorPatchAction::ConvertToWorld: return "convert_to_world";
    case SectorPatchAction::ConvertToChild: return "convert_to_child";
    case SectorPatchAction::ReplaceName: return "replace_name";
    default: return "unknown";
    }
}

void SectorPatchQueue::enqueue(const SectorPatchRequest& request) {
    requests_.push_back(request);
}

void SectorPatchQueue::clear() {
    requests_.clear();
}

static std::string jsonEscape(const std::string& s) {
    std::ostringstream out;
    for (char c : s) {
        switch (c) {
        case '\\': out << "\\\\"; break;
        case '"': out << "\\\""; break;
        case '\n': out << "\\n"; break;
        case '\r': out << "\\r"; break;
        case '\t': out << "\\t"; break;
        default: out << c; break;
        }
    }
    return out.str();
}

std::string SectorPatchQueue::exportJson() const {
    std::ostringstream out;
    out << "{\n  \"schema\": \"CodeRED.RemoteMenu.SectorPatchQueue.v1\",\n  \"requests\": [\n";
    for (std::size_t i = 0; i < requests_.size(); ++i) {
        const auto& r = requests_[i];
        out << "    {\n";
        out << "      \"action\": \"" << jsonEscape(toString(r.action)) << "\",\n";
        out << "      \"parent\": \"" << jsonEscape(r.parent) << "\",\n";
        out << "      \"sector_name\": \"" << jsonEscape(r.sectorName) << "\",\n";
        out << "      \"replacement_name\": \"" << jsonEscape(r.replacementName) << "\",\n";
        out << "      \"current_kind\": \"" << jsonEscape(toString(r.currentKind)) << "\",\n";
        out << "      \"desired_kind\": \"" << jsonEscape(toString(r.desiredKind)) << "\",\n";
        out << "      \"target_wsc_path\": \"" << jsonEscape(r.targetWscPath) << "\"\n";
        out << "    }" << (i + 1 == requests_.size() ? "" : ",") << "\n";
    }
    out << "  ]\n}\n";
    return out.str();
}

std::string SectorPatchQueue::exportWorkbenchCommands(const std::string& workbenchPy) const {
    std::ostringstream out;
    out << "# Review before running. Generated by Code RED Remote Menu.\n";
    for (const auto& r : requests_) {
        out << "python \"" << workbenchPy << "\" sector-patch \"" << r.targetWscPath << "\" --sector \"" << r.sectorName << "\" ";
        switch (r.action) {
        case SectorPatchAction::Enable: out << "--enable"; break;
        case SectorPatchAction::Disable: out << "--disable"; break;
        case SectorPatchAction::ConvertToWorld: out << "--to-world"; break;
        case SectorPatchAction::ConvertToChild: out << "--to-child"; break;
        case SectorPatchAction::ReplaceName: out << "--replace-name \"" << r.replacementName << "\""; break;
        }
        out << " --out patched\n";
    }
    return out.str();
}

} // namespace codered
